---
# vars file for ace.icinga2
- name: "Install EPEL and centos-release-scl"
  yum: name={{item}} state=installed
  with_items:
    - epel-release
    - centos-release-scl
    - https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm

- name: "Install Required Packages"
  yum: name={{item}} state=installed
  with_items:
    - icinga2
    - icinga2-ido-mysql
    - icingacli
    - nagios-plugins-all 

- name: "Set hostname like wanted"
  hostname: name="{{hostname}}"
    
- name: start icinga2 on boot
  service: name={{item}} state=started enabled=yes
  with_items:
    - icinga2

#- name: SeLinux Config
#  lineinfile:
#    dest: /etc/sysconfig/selinux 
#    regexp: "SELINUX=enforcing"
#    line: "SELINUX=disabled"
  